CC=g++

all:
	$(CC) cpp_Polymorphism.cpp -o test1.o
	$(CC) hkr_minimum_operator.cpp -o test2.o
	$(CC) hkr_zigzac.cpp -o test3.o
	$(CC) hkr_flippingBits.cpp -o test4.o
	$(CC) hkr_YetAnotherMinimax.cpp -o test5.o
	$(CC) hkr_between2sets.cpp -o test6.o

clean:
	rm *.o